purposes:
  - description: ブラウザアプリケーションのロジック層を書ける
    requirements:
      - skill: tech
        level: 2
      - skill: application
        level: 3
  - description: ブラウザアプリケーションのView層を書ける
    requirements:
      - skill: visual
        level: 2
      - skill: express
        level: 3
      - skill: application
        level: 1
  - description: ブラウザアプリケーションの設計・構築を行える
    requirements:
      - skill: tech
        level: 4
      - skill: application
        level: 5
      - skill: semantic
        level: 2
  - description: 思い通りのサイトをpain-freeで作れる
    requirements:
      - skill: visual
        level: 4
      - skill: express
        level: 4
      - skill: application
        level: 1
      - skill: application
        level: 1
  - description: ブラウザゲームを作れる
    requirements:
      - skill: tech
        level: 4
      - skill: application
        level: 2
  - description: 今までにないWeb体験を作っていける
    requirements:
      - skill: tech
        level: 5
      - skill: application
        level: 2
  - description: Webならではの表現力をもったサイトを作れる
    requirements:
      - skill: visual
        level: 3
      - skill: express
        level: 5
      - skill: tech
        level: 4
  - description: アクセシビリティが高いサイトを作れる
    requirements:
      - skill: visual
        level: 1
      - skill: semantic
        level: 4
  - description: 思い通りのデザイン/インタラクションを備えたサイトを作れる
    requirements:
      - skill: visual
        level: 5
      - skill: express
        level: 5
  - description: 最適化されたサイトを制作できる
    requirements:
      - skill: semantic
        level: 5
  - description: サーバサイドWebアプリの静的ファイルにインタラクションを付与できる
    requirements:
      - skill: express
        level: 3
      - skill: tech
        level: 1
      - skill: application
        level: 1
